FROM arm64v8/alpine:3.12 as alpine
RUN apk add -U --no-cache ca-certificates


FROM arm64v8/alpine:3.12

ENV GODEBUG netdns=go
COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# Install jfrog cli with version 1.35.5
RUN apk add --update \
    curl \
    && rm -rf /var/cache/apk/*
RUN curl -fL https://getcli.jfrog.io | sh /dev/stdin 2.36.1
RUN mv ./jfrog /usr/local/bin/
RUN chmod +x /usr/local/bin/jfrog

ADD release/linux/arm64/plugin /bin/
ENTRYPOINT ["/bin/plugin"]
