# escape=`
FROM golang:1.17.3 as builder
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

WORKDIR /src
ENV CGO_ENABLED=0
COPY . .
RUN go build -o drone-artifactory.exe .

FROM mcr.microsoft.com/windows/nanoserver:1903
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
USER ContainerAdministrator

ENV GODEBUG=netdns=go

RUN choco install jfrog-cli

COPY --from=builder /src/drone-artifactory.exe C:/drone-artifactory.exe
ENTRYPOINT [ "C:\\drone-artifactory.exe" ]