# escape=`

FROM FROM mcr.microsoft.com/powershell:7.2.1-nanoserver-1809-20211215
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
USER ContainerAdministrator

ENV GODEBUG=netdns=go

RUN choco install jfrog-cli
RUN Invoke-WebRequest https://releases.jfrog.io/artifactory/jfrog-cli/v2/1.35.5/jfrog-cli-windows-amd64/jfrog.exe -OutFile C:/bin/jfrog.exe

COPY --from=builder release/windows/amd64/plugin C:/bin/drone-artifactory.exe
ENTRYPOINT [ "C:\\bin\\drone-artifactory.exe" ]