FROM alpine:3.17 as alpine
RUN apk add -U --no-cache ca-certificates

FROM alpine:3.17
ENV GODEBUG netdns=go
ENV CI=true
COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# Install jfrog cli with version 2.37.3
RUN apk add --update \
    curl \
    && rm -rf /var/cache/apk/*
RUN curl -fL https://getcli.jfrog.io/v2-jf | sh /dev/stdin 2.52.9
RUN mv ./jf /usr/local/bin/jfrog
RUN chmod +x /usr/local/bin/jfrog

ADD release/linux/amd64/plugin /bin/
ENTRYPOINT ["/bin/plugin"]
